NTXSolution.MVC/ViewModels/LivroViewModel.cs
using NTXSolution.Domain.Entities;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace NTXSolution.MVC.ViewModels
{
    public class LivroViewModel
    {
              
        [Key]
        public int LivroId { get; set; }

        [Required(ErrorMessage = "Preencha o campo Nome")]
        [MaxLength(250, ErrorMessage = "Máximo {0} caracteres")]
        [MinLength(2, ErrorMessage = "Mínimo {0} caracteres")]
        public string Nome { get; set; }


        public string Autor { get; set; }
        public string Idioma { get; set; }
        public int Paginas { get; set; }
        public string Capa { get; set; }

        /*
        [DataType(DataType.Currency)]
         [Range(typeof(decimal), "0", "999999999999")]
        [Required(ErrorMessage = "Preencha um valor")]
        public decimal Valor { get; set; }*

        [DisplayName("Disponivel?")]

        public bool Disponivel { get; set; }*/

        public int EditoraId { get; set; }
        public virtual EditoraViewModel Editora { get; set; }
    }

    internal class ctor
    {
    }
}

NTXSolution.MVC/Controllers/LivrosController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using NTXSolution.Application.Interface;
using NTXSolution.Domain.Entities;
using NTXSolution.MVC.ViewModels;
using System.Linq;
using System;

namespace NTXSolution.MVC.Controllers
{
    public class LivrosController : Controller
    {
        // GET: Livros
        private readonly ILivroAppService _LivroApp;
        private readonly IEditoraAppService _EditoraApp;
        private readonly IdiomaViewModel _idiomaview;
        public LivrosController(ILivroAppService LivroApp, IEditoraAppService EditoraApp)
        {
            _LivroApp = LivroApp;
            _EditoraApp = EditoraApp;
        }

        // GET: Editora
        public ActionResult Index()
        {
            var LivroViewModel = Mapper.Map<IEnumerable<Livro>, IEnumerable<LivroViewModel>>(_LivroApp.GetAll());

            return View(LivroViewModel);
        }

        

        // GET: Editora/Details/5
        public ActionResult Details(int id)
        {
            var Livro = _LivroApp.GetById(id);
            var LivroViewModel = Mapper.Map<Livro, LivroViewModel>(Livro);

            return View(LivroViewModel);
        }

        // GET: Editora/Create
        public ActionResult Create()
        {
            ViewBag.EditoraId = new SelectList(_EditoraApp.GetAll(), "EditoraId", "Nome");
            //Iniciando a criação dos Comboc para Validar
            Idioma[] values = (Idioma[])Enum.GetValues(typeof(Idioma));
            var valuesWithNames = from value in values
                                  select new { name = value.ToString(), value = (int)value };
            ViewBag.IdiomaId = valuesWithNames;
            return View();
        }

        // POST: Editora/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LivroViewModel Livro)
        {
            if (ModelState.IsValid)
            {
                var LivroDomain = Mapper.Map<LivroViewModel, Livro>(Livro);
                _LivroApp.Add(LivroDomain);

                return RedirectToAction("Index");
            }

            ViewBag.EditoraId = new SelectList(_EditoraApp.GetAll(), "EditoraId", "Nome", Livro.EditoraId);
            return View(Livro);
        }

        // GET: Editora/Edit/5
        public ActionResult Edit(int id)
        {
            var Livro = _LivroApp.GetById(id);
            var LivroViewModel = Mapper.Map<Livro, LivroViewModel>(Livro);

            ViewBag.EditoraId = new SelectList(_EditoraApp.GetAll(), "EditoraId", "Nome", LivroViewModel.EditoraId);

            return View(LivroViewModel);
        }

        public ActionResult ConsultaPorNome(string Nome)
        {
            var LivroViewModel = Mapper.Map<IEnumerable<Livro>, IEnumerable<LivroViewModel>>(_LivroApp.BuscarPorNome(Nome));

            return View(LivroViewModel);
        }

        public ActionResult ConsultaPorAutor(string Autor)
        {
            var LivroViewModel = Mapper.Map<IEnumerable<Livro>, IEnumerable<LivroViewModel>>(_LivroApp.BuscarPorAutor(Autor));

            return View(LivroViewModel);
        }

        // POST: Editora/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LivroViewModel Livro)
        {
            if (ModelState.IsValid)
            {
                var LivroDomain = Mapper.Map<LivroViewModel, Livro>(Livro);
                _LivroApp.Update(LivroDomain);

                return RedirectToAction("Index");
            }

            ViewBag.EditoraId = new SelectList(_EditoraApp.GetAll(), "EditoraId", "Nome", Livro.EditoraId);
            return View(Livro);
        }

        // GET: Editora/Delete/5
        public ActionResult Delete(int id)
        {
            var Livro = _LivroApp.GetById(id);
            var LivroViewModel = Mapper.Map<Livro, LivroViewModel>(Livro);

            return View(LivroViewModel);
        }

        // POST: Editora/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var Livro = _LivroApp.GetById(id);
            _LivroApp.Remove(Livro);

            return RedirectToAction("Index");
        }
    }
}

NTXSolution.MVC/Views/Livros/ConsultaPorAutor.cshtml
@model IEnumerable<NTXSolution.MVC.ViewModels.LivroViewModel>

@{
    ViewBag.Title = "ConsultaPorAutor";
}

<h2>ConsultaPorAutor</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idioma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paginas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EditoraId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Idioma)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paginas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EditoraId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LivroId }) |
            @Html.ActionLink("Details", "Details", new { id=item.LivroId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LivroId })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

NTXSolution.MVC/Views/Livros/ConsultaPorNome.cshtml
@model IEnumerable<NTXSolution.MVC.ViewModels.LivroViewModel>

@{
    ViewBag.Title = "ConsultaPorNome";
}

<h2>ConsultaPorNome</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idioma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paginas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EditoraId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Idioma)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paginas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EditoraId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LivroId }) |
            @Html.ActionLink("Details", "Details", new { id=item.LivroId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LivroId })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

NTXSolution.MVC/Views/Livros/Create.cshtml
@model NTXSolution.MVC.ViewModels.LivroViewModel


@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LivroViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

       <div class="form-group">
            @Html.LabelFor(model => model.Idioma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Idioma)
                    @Html.ValidationMessageFor(model => model.Idioma, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Paginas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Paginas)
                    @Html.ValidationMessageFor(model => model.Paginas, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Capa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Capa)
                    @Html.ValidationMessageFor(model => model.Capa, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    

        <div class="form-group">
            @Html.LabelFor(model => model.EditoraId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EditoraId", String.Empty)
                @Html.ValidationMessageFor(model => model.EditoraId, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NTXSolution.MVC/Views/Livros/Delete.cshtml
@model NTXSolution.MVC.ViewModels.LivroViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LivroViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idioma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idioma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paginas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paginas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EditoraId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EditoraId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NTXSolution.MVC/Views/Livros/Details.cshtml
@model NTXSolution.MVC.ViewModels.LivroViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LivroViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idioma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idioma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paginas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paginas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EditoraId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EditoraId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LivroId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NTXSolution.MVC/Views/Livros/Edit.cshtml
@model NTXSolution.MVC.ViewModels.LivroViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LivroViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LivroId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idioma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Idioma)
                    @Html.ValidationMessageFor(model => model.Idioma, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Paginas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Paginas)
                    @Html.ValidationMessageFor(model => model.Paginas, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Capa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Capa)
                    @Html.ValidationMessageFor(model => model.Capa, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EditoraId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EditoraId", String.Empty)
                @Html.ValidationMessageFor(model => model.EditoraId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NTXSolution.MVC/Views/Livros/Index.cshtml
@model IEnumerable<NTXSolution.MVC.ViewModels.LivroViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
   Pesquisar Por Nome
    @using(Html.BeginForm("ConsultaPorNome","Livros", FormMethod.Get))
    {
        @Html.TextBox("Nome")
        <input type="submit" value="Pesquisar"/>
    }
</p>

<p>
    Pesquisar Por Autor
    @using (Html.BeginForm("ConsultaPorAutor", "Livros", FormMethod.Get))
    {
        @Html.TextBox("Autor")
        <input type="submit" value="AutorPesquisa" />
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idioma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paginas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capa)
        </th>
        <th>
            @Html.DisplayName("Editora")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Idioma)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paginas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Editora.Nome)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LivroId }) |
            @Html.ActionLink("Details", "Details", new { id=item.LivroId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LivroId })
        </td>
    </tr>
}

</table>